Refactor for blender2.8 API
wisaac407/blender-script-watcher pull request #5
Opened 2019-01-28 19:52 UTC by ranjian0

Made some basic changes to allow use in blender 2.8

2019-07-07 23:00 UTC, wisaac407 requested changes
Sorry for the (extremely) late response to this, I'm just recently getting back into Blender stuff. Thanks for submitting the pull request, I took a look over it and it looks good except for a few minor changes.

2019-07-07 23:00 UTC, wisaac407 commented on script_watcher.py
> +    editor_path : bpy.props.StringProperty(
It would be best to keep it backward compatible with Blender 2.79. This [article](https://theduckcow.com/2019/update-addons-both-blender-28-and-27-support/) explains how to do that. The basic idea is to keep using the old method than convert to annotations if it's Blender 2.80

The conversion can be accomplished by inserting this code:

```python
def make_annotations(cls):
    """Converts class fields to annotations if running with Blender 2.8"""
    if bpy.app.version < (2, 80):
        return cls
    bl_props = {k: v for k, v in cls.__dict__.items() if isinstance(v, tuple)}
    if bl_props:
        if '__annotations__' not in cls.__dict__:
            setattr(cls, '__annotations__', {})
        annotations = cls.__dict__['__annotations__']
        for k, v in bl_props.items():
            annotations[k] = v
            delattr(cls, k)
    return cls
```

And then adding the `make_annotations` decorator to each class. E.g:

```python
@make_annotations
class ScriptWatcherPreferences(bpy.types.AddonPreferences):
    bl_idname = __name__
```

2019-07-07 23:00 UTC, wisaac407 commented on script_watcher.py
> +                pass
What's the rationale for wrapping this in a try/except? I haven't tested it on 2.80 yet, but it shouldn't be throwing a type error.

2019-07-09 20:28 UTC, ranjian0 commented on script_watcher.py
> +                pass
My thoughts exactly. I never got the time to investigate the problem closely and admittedly this was a lazy fix. Perhaps you should test in 2.80 and have a closer look.

2019-07-09 20:55 UTC, ranjian0 commented on script_watcher.py
> +                pass
Just tested it, the issue no longer exists. Blender 2.80 was quite unstable when I made this and if I remember correctly there was a conflict with one of blender's internal addon.

2019-07-09 21:26 UTC, ranjian0 commented on script_watcher.py
> +    editor_path : bpy.props.StringProperty(
Done

2019-07-09 21:50 UTC, wisaac407 commented on script_watcher.py
> +                pass
Ok, that makes sense

2019-07-09 21:51 UTC, wisaac407 commented
Looks good!

2019-07-09 21:51 UTC, merged